In [1]:
import numpy as np
import scipy.linalg

In [2]:
a = np.array([[1.,2.,3.], [4.,5.,6.]])
print a

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [3]:
np.ndim(a)   #a.ndim

2

In [4]:
np.size(a)     #a.size

6

In [5]:
np.shape(a)   #a.shape

(2, 3)

In [6]:
b = np.array([[1.,2.],[3.,4.]])
print "hstack([a,b]): "+str(np.hstack([a,b]))
c = np.array([[1.1, 1.2], [1.3, 1.4], [1.5, 1.6]])
d = np.array([[2.1,2.2,2.3],[2.4,2.5,2.6],[2.7,2.8,2.9]])
print "np.hstack([c,d]): "+str(np.hstack([c,d]))
print "result: "+str(np.vstack([np.hstack([a,b]), np.hstack([c,d])]))

hstack([a,b]): [[ 1.  2.  3.  1.  2.]
 [ 4.  5.  6.  3.  4.]]
np.hstack([c,d]): [[ 1.1  1.2  2.1  2.2  2.3]
 [ 1.3  1.4  2.4  2.5  2.6]
 [ 1.5  1.6  2.7  2.8  2.9]]
result: [[ 1.   2.   3.   1.   2. ]
 [ 4.   5.   6.   3.   4. ]
 [ 1.1  1.2  2.1  2.2  2.3]
 [ 1.3  1.4  2.4  2.5  2.6]
 [ 1.5  1.6  2.7  2.8  2.9]]


In [7]:
a = np.vstack([np.hstack([a,b]), np.hstack([c,d])])
print a

[[ 1.   2.   3.   1.   2. ]
 [ 4.   5.   6.   3.   4. ]
 [ 1.1  1.2  2.1  2.2  2.3]
 [ 1.3  1.4  2.4  2.5  2.6]
 [ 1.5  1.6  2.7  2.8  2.9]]


In [8]:
a[-1]

array([ 1.5,  1.6,  2.7,  2.8,  2.9])

In [9]:
a[1,2]

6.0

In [10]:
a[1]

array([ 4.,  5.,  6.,  3.,  4.])

In [11]:
a[0:2]

array([[ 1.,  2.,  3.,  1.,  2.],
       [ 4.,  5.,  6.,  3.,  4.]])

In [12]:
a[-2:]

array([[ 1.3,  1.4,  2.4,  2.5,  2.6],
       [ 1.5,  1.6,  2.7,  2.8,  2.9]])

In [13]:
a[0:3][:,1:4]

array([[ 2. ,  3. ,  1. ],
       [ 5. ,  6. ,  3. ],
       [ 1.2,  2.1,  2.2]])

In [14]:
a[np.ix_([0,1,3],[0,2])]

array([[ 1. ,  3. ],
       [ 4. ,  6. ],
       [ 1.3,  2.4]])

In [15]:
a[ 1:5:2,:]

array([[ 4. ,  5. ,  6. ,  3. ,  4. ],
       [ 1.3,  1.4,  2.4,  2.5,  2.6]])

In [16]:
a[ ::2,:]

array([[ 1. ,  2. ,  3. ,  1. ,  2. ],
       [ 1.1,  1.2,  2.1,  2.2,  2.3],
       [ 1.5,  1.6,  2.7,  2.8,  2.9]])

In [17]:
a[ ::-1,:]

array([[ 1.5,  1.6,  2.7,  2.8,  2.9],
       [ 1.3,  1.4,  2.4,  2.5,  2.6],
       [ 1.1,  1.2,  2.1,  2.2,  2.3],
       [ 4. ,  5. ,  6. ,  3. ,  4. ],
       [ 1. ,  2. ,  3. ,  1. ,  2. ]])

In [18]:
a[np.r_[:len(a),0]]

array([[ 1. ,  2. ,  3. ,  1. ,  2. ],
       [ 4. ,  5. ,  6. ,  3. ,  4. ],
       [ 1.1,  1.2,  2.1,  2.2,  2.3],
       [ 1.3,  1.4,  2.4,  2.5,  2.6],
       [ 1.5,  1.6,  2.7,  2.8,  2.9],
       [ 1. ,  2. ,  3. ,  1. ,  2. ]])

In [19]:
a.transpose()

array([[ 1. ,  4. ,  1.1,  1.3,  1.5],
       [ 2. ,  5. ,  1.2,  1.4,  1.6],
       [ 3. ,  6. ,  2.1,  2.4,  2.7],
       [ 1. ,  3. ,  2.2,  2.5,  2.8],
       [ 2. ,  4. ,  2.3,  2.6,  2.9]])

In [20]:
a.conj().transpose()

array([[ 1. ,  4. ,  1.1,  1.3,  1.5],
       [ 2. ,  5. ,  1.2,  1.4,  1.6],
       [ 3. ,  6. ,  2.1,  2.4,  2.7],
       [ 1. ,  3. ,  2.2,  2.5,  2.8],
       [ 2. ,  4. ,  2.3,  2.6,  2.9]])

In [21]:
print "a: "+str(a)
b = np.array([2,2,2,2,2])
a.dot(b)

a: [[ 1.   2.   3.   1.   2. ]
 [ 4.   5.   6.   3.   4. ]
 [ 1.1  1.2  2.1  2.2  2.3]
 [ 1.3  1.4  2.4  2.5  2.6]
 [ 1.5  1.6  2.7  2.8  2.9]]


array([ 18. ,  44. ,  17.8,  20.4,  23. ])

In [22]:
a * b

array([[  2. ,   4. ,   6. ,   2. ,   4. ],
       [  8. ,  10. ,  12. ,   6. ,   8. ],
       [  2.2,   2.4,   4.2,   4.4,   4.6],
       [  2.6,   2.8,   4.8,   5. ,   5.2],
       [  3. ,   3.2,   5.4,   5.6,   5.8]])

In [23]:
a/b

array([[ 0.5 ,  1.  ,  1.5 ,  0.5 ,  1.  ],
       [ 2.  ,  2.5 ,  3.  ,  1.5 ,  2.  ],
       [ 0.55,  0.6 ,  1.05,  1.1 ,  1.15],
       [ 0.65,  0.7 ,  1.2 ,  1.25,  1.3 ],
       [ 0.75,  0.8 ,  1.35,  1.4 ,  1.45]])

In [24]:
a**3

array([[   1.   ,    8.   ,   27.   ,    1.   ,    8.   ],
       [  64.   ,  125.   ,  216.   ,   27.   ,   64.   ],
       [   1.331,    1.728,    9.261,   10.648,   12.167],
       [   2.197,    2.744,   13.824,   15.625,   17.576],
       [   3.375,    4.096,   19.683,   21.952,   24.389]])

In [25]:
(a>2)

array([[False, False,  True, False, False],
       [ True,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True]], dtype=bool)

In [26]:
np.nonzero(a>2)

(array([0, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]),
 array([2, 0, 1, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4]))

In [27]:
v = np.array([[0.1, 0.8, 0.5],[0.7,0.5,0.2]])
print v

[[ 0.1  0.8  0.5]
 [ 0.7  0.5  0.2]]


In [28]:
a[:,np.nonzero(v>0.5)[0]]

array([[ 1. ,  2. ],
       [ 4. ,  5. ],
       [ 1.1,  1.2],
       [ 1.3,  1.4],
       [ 1.5,  1.6]])

In [29]:
a[a<1.5]=0
print a

[[ 0.   2.   3.   0.   2. ]
 [ 4.   5.   6.   3.   4. ]
 [ 0.   0.   2.1  2.2  2.3]
 [ 0.   0.   2.4  2.5  2.6]
 [ 1.5  1.6  2.7  2.8  2.9]]


In [30]:
a * (a>0.5)

array([[ 0. ,  2. ,  3. ,  0. ,  2. ],
       [ 4. ,  5. ,  6. ,  3. ,  4. ],
       [ 0. ,  0. ,  2.1,  2.2,  2.3],
       [ 0. ,  0. ,  2.4,  2.5,  2.6],
       [ 1.5,  1.6,  2.7,  2.8,  2.9]])

In [31]:
temp = a.copy()
temp[:] = 3
print temp

[[ 3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.]]


In [32]:
temp = a.flatten()
print temp

[ 0.   2.   3.   0.   2.   4.   5.   6.   3.   4.   0.   0.   2.1  2.2  2.3
  0.   0.   2.4  2.5  2.6  1.5  1.6  2.7  2.8  2.9]


In [33]:
np.arange(1.,11.)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [34]:
np.arange(10.)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [35]:
np.arange(1.,11.)[:, np.newaxis]

array([[  1.],
       [  2.],
       [  3.],
       [  4.],
       [  5.],
       [  6.],
       [  7.],
       [  8.],
       [  9.],
       [ 10.]])

In [36]:
np.	zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [37]:
np.zeros((3,4,5))

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [38]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [39]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [40]:
a

array([[ 0. ,  2. ,  3. ,  0. ,  2. ],
       [ 4. ,  5. ,  6. ,  3. ,  4. ],
       [ 0. ,  0. ,  2.1,  2.2,  2.3],
       [ 0. ,  0. ,  2.4,  2.5,  2.6],
       [ 1.5,  1.6,  2.7,  2.8,  2.9]])

In [41]:
np.diag(a)

array([ 0. ,  5. ,  2.1,  2.5,  2.9])

In [42]:
np.diag(a,0)

array([ 0. ,  5. ,  2.1,  2.5,  2.9])

In [43]:
np.random.rand(3,4)

array([[ 0.78514349,  0.8528791 ,  0.37633085,  0.09985496],
       [ 0.48260466,  0.26515346,  0.63029861,  0.90512229],
       [ 0.89709534,  0.62225965,  0.39720993,  0.99514208]])

In [44]:
np.linspace(1,3,4)

array([ 1.        ,  1.66666667,  2.33333333,  3.        ])

In [45]:
np.mgrid[0:9.,0:6.]

array([[[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.,  8.,  8.]],

       [[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 0.,  1.,  2.,  3.,  4.,  5.]]])

In [46]:
np.ogrid[0:9.,0:6.] 

[array([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.]]), array([[ 0.,  1.,  2.,  3.,  4.,  5.]])]

In [47]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]), array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [48]:
m = 2
n = 3
np.tile(a, (m, n))

array([[ 0. ,  2. ,  3. ,  0. ,  2. ,  0. ,  2. ,  3. ,  0. ,  2. ,  0. ,
         2. ,  3. ,  0. ,  2. ],
       [ 4. ,  5. ,  6. ,  3. ,  4. ,  4. ,  5. ,  6. ,  3. ,  4. ,  4. ,
         5. ,  6. ,  3. ,  4. ],
       [ 0. ,  0. ,  2.1,  2.2,  2.3,  0. ,  0. ,  2.1,  2.2,  2.3,  0. ,
         0. ,  2.1,  2.2,  2.3],
       [ 0. ,  0. ,  2.4,  2.5,  2.6,  0. ,  0. ,  2.4,  2.5,  2.6,  0. ,
         0. ,  2.4,  2.5,  2.6],
       [ 1.5,  1.6,  2.7,  2.8,  2.9,  1.5,  1.6,  2.7,  2.8,  2.9,  1.5,
         1.6,  2.7,  2.8,  2.9],
       [ 0. ,  2. ,  3. ,  0. ,  2. ,  0. ,  2. ,  3. ,  0. ,  2. ,  0. ,
         2. ,  3. ,  0. ,  2. ],
       [ 4. ,  5. ,  6. ,  3. ,  4. ,  4. ,  5. ,  6. ,  3. ,  4. ,  4. ,
         5. ,  6. ,  3. ,  4. ],
       [ 0. ,  0. ,  2.1,  2.2,  2.3,  0. ,  0. ,  2.1,  2.2,  2.3,  0. ,
         0. ,  2.1,  2.2,  2.3],
       [ 0. ,  0. ,  2.4,  2.5,  2.6,  0. ,  0. ,  2.4,  2.5,  2.6,  0. ,
         0. ,  2.4,  2.5,  2.6],
       [ 1.5,  1.6,  2.7,  2.8,  2.9,

In [49]:
b = np.eye(5)

In [50]:
np.concatenate((a,b),1)

array([[ 0. ,  2. ,  3. ,  0. ,  2. ,  1. ,  0. ,  0. ,  0. ,  0. ],
       [ 4. ,  5. ,  6. ,  3. ,  4. ,  0. ,  1. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  2.1,  2.2,  2.3,  0. ,  0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  2.4,  2.5,  2.6,  0. ,  0. ,  0. ,  1. ,  0. ],
       [ 1.5,  1.6,  2.7,  2.8,  2.9,  0. ,  0. ,  0. ,  0. ,  1. ]])

In [51]:
np.concatenate((a,b))

array([[ 0. ,  2. ,  3. ,  0. ,  2. ],
       [ 4. ,  5. ,  6. ,  3. ,  4. ],
       [ 0. ,  0. ,  2.1,  2.2,  2.3],
       [ 0. ,  0. ,  2.4,  2.5,  2.6],
       [ 1.5,  1.6,  2.7,  2.8,  2.9],
       [ 1. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  1. ]])

In [52]:
a.max()

6.0

In [53]:
a.max(0)

array([ 4.,  5.,  6.,  3.,  4.])

In [54]:
a.max(1)

array([ 3. ,  6. ,  2.3,  2.6,  2.9])

In [55]:
np.maximum(a, b)

array([[ 1. ,  2. ,  3. ,  0. ,  2. ],
       [ 4. ,  5. ,  6. ,  3. ,  4. ],
       [ 0. ,  0. ,  2.1,  2.2,  2.3],
       [ 0. ,  0. ,  2.4,  2.5,  2.6],
       [ 1.5,  1.6,  2.7,  2.8,  2.9]])

In [56]:
np.sqrt(np.dot(a,a))

array([[ 3.31662479,  3.63318042,  4.86826458,  4.2661458 ,  4.54972527],
       [ 5.09901951,  6.27694193,  8.52056336,  6.84835747,  7.82304289],
       [ 1.85741756,  1.91833261,  3.98748041,  4.06939799,  4.14969878],
       [ 1.97484177,  2.03960781,  4.24970587,  4.33704969,  4.42266888],
       [ 3.27871926,  3.95474399,  5.85832741,  5.08527285,  5.59464029]])

In [57]:
np.logical_and(a,b)

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]], dtype=bool)

In [58]:
np.logical_or(a,b)

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [59]:
(a>0) & (b>0)

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]], dtype=bool)

In [60]:
(a>0) | (b>0)

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [61]:
np.linalg.inv(a)

array([[ -0.98461538,   1.23076923,  71.23076923, -61.23076923,
         -2.61538462],
       [  0.92307692,  -1.15384615, -66.15384615,  56.15384615,
          3.07692308],
       [ -0.16923077,   0.46153846,  -6.87179487,   6.87179487,
         -1.23076923],
       [  0.33846154,  -0.92307692, -72.92307692,  62.92307692,
          2.46153846],
       [ -0.16923077,   0.46153846,  76.46153846, -66.46153846,
         -1.23076923]])

In [62]:
np.linalg.pinv(a)

array([[ -0.98461538,   1.23076923,  71.23076923, -61.23076923,
         -2.61538462],
       [  0.92307692,  -1.15384615, -66.15384615,  56.15384615,
          3.07692308],
       [ -0.16923077,   0.46153846,  -6.87179487,   6.87179487,
         -1.23076923],
       [  0.33846154,  -0.92307692, -72.92307692,  62.92307692,
          2.46153846],
       [ -0.16923077,   0.46153846,  76.46153846, -66.46153846,
         -1.23076923]])

In [63]:
np.linalg.matrix_rank(a)

5

In [64]:
np.linalg.solve(a,b)

array([[ -0.98461538,   1.23076923,  71.23076923, -61.23076923,
         -2.61538462],
       [  0.92307692,  -1.15384615, -66.15384615,  56.15384615,
          3.07692308],
       [ -0.16923077,   0.46153846,  -6.87179487,   6.87179487,
         -1.23076923],
       [  0.33846154,  -0.92307692, -72.92307692,  62.92307692,
          2.46153846],
       [ -0.16923077,   0.46153846,  76.46153846, -66.46153846,
         -1.23076923]])

In [65]:
U, S, Vh = np.linalg.svd(a)
V = Vh.T
print U
print '---------------------------------------'
print S
print '---------------------------------------'
print V

[[-0.28390596 -0.14797044  0.91311559  0.25235783  0.0061315 ]
 [-0.77865013 -0.4834259  -0.22995655 -0.32715509 -0.00963846]
 [-0.25333333  0.54633775  0.08087488 -0.23888625 -0.75744961]
 [-0.2880173   0.61944031  0.09342736 -0.31471525  0.65235373]
 [-0.40739371  0.24942518 -0.31316207  0.82047105  0.02396278]]
---------------------------------------
[  1.27506248e+01   3.69250608e+00   2.07446154e+00   3.78878074e-01
   5.26959290e-03]
---------------------------------------
[[-0.29219675 -0.42235972 -0.66984578 -0.20564343 -0.49522796]
 [-0.40099153 -0.62667197  0.08454681  0.47955768  0.45756343]
 [-0.61540696 -0.01003457  0.43776795 -0.65341057  0.05086686]
 [-0.37284678  0.54127375 -0.55688202  0.00927948  0.50774434]
 [-0.48588724  0.36853295  0.20591286  0.54836459 -0.53384756]]


In [66]:
np.linalg.cholesky(np.eye(5)).T

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [67]:
D,V = np.linalg.eig(a)
print D
print '---------------------------------------'
print V

[ 10.03392042   3.69674136  -1.42608758   0.17427296   0.02115284]
---------------------------------------
[[ 0.29261029  0.28643223 -0.82949377 -0.35346671 -0.48223986]
 [ 0.84071901  0.84575338  0.50314793  0.18903491  0.4323202 ]
 [ 0.16232886 -0.28695168 -0.08123176  0.33267995  0.08251115]
 [ 0.18416362 -0.32756086 -0.08952246  0.46032499  0.50872851]
 [ 0.38380186  0.11410708  0.2101651  -0.71885468 -0.5611873 ]]


In [68]:
Q,R = scipy.linalg.qr(a)
print Q
print '---------------------------------------'
print R

[[ 0.          0.99181395 -0.03110536  0.12383355  0.0016703 ]
 [-0.93632918  0.04483543  0.0848328  -0.33772785 -0.00455536]
 [-0.          0.         -0.638668   -0.15024579 -0.75467171]
 [-0.          0.         -0.72990629 -0.19219079  0.65597219]
 [-0.35112344 -0.11956113 -0.22622079  0.9006076   0.01214763]]
---------------------------------------
[[-4.27200187 -5.24344339 -6.56600836 -3.79213317 -4.76357469]
 [ 0.          2.01650722  2.92163935 -0.2002649   1.81624232]
 [ 0.          0.         -3.28809333 -3.60875515 -3.74561258]
 [ 0.          0.          0.          0.69750002  0.66325636]
 [ 0.          0.          0.          0.         -0.00986995]]


In [69]:
LU,P=scipy.linalg.lu_factor(a)
print LU
print '---------------------------------------'
print P

[[ 4.          5.          6.          3.          4.        ]
 [ 0.          2.          3.          0.          2.        ]
 [ 0.          0.          2.4         2.5         2.6       ]
 [ 0.375      -0.1375      0.359375    0.7765625   0.740625  ]
 [ 0.          0.          0.875       0.01609658  0.01307847]]
---------------------------------------
[1 1 3 4 4]


In [70]:
scipy.fft(a)

array([[  7.00000000+0.j        ,  -1.19098301-1.76335576j,
         -2.30901699+2.85316955j,  -2.30901699-2.85316955j,
         -1.19098301+1.76335576j],
       [ 22.00000000+0.j        ,  -0.50000000-2.71441227j,
         -0.50000000+2.2653843j ,  -0.50000000-2.2653843j ,
         -0.50000000+2.71441227j],
       [  6.60000000+0.j        ,  -2.76803399+2.24620851j,
         -0.53196601+1.25680043j,  -0.53196601-1.25680043j,
         -2.76803399-2.24620851j],
       [  7.50000000+0.j        ,  -3.16073909+2.53152547j,
         -0.58926091+1.433136j  ,  -0.58926091-1.433136j  ,
         -3.16073909-2.53152547j],
       [ 11.50000000+0.j        ,  -1.55901699+1.295152j  ,
         -0.44098301+0.66901518j,  -0.44098301-0.66901518j,
         -1.55901699-1.295152j  ]])

In [71]:
scipy.ifft(a)

array([[ 1.40000000+0.j        , -0.23819660+0.35267115j,
        -0.46180340-0.57063391j, -0.46180340+0.57063391j,
        -0.23819660-0.35267115j],
       [ 4.40000000+0.j        , -0.10000000+0.54288245j,
        -0.10000000-0.45307686j, -0.10000000+0.45307686j,
        -0.10000000-0.54288245j],
       [ 1.32000000+0.j        , -0.55360680-0.4492417j ,
        -0.10639320-0.25136009j, -0.10639320+0.25136009j,
        -0.55360680+0.4492417j ],
       [ 1.50000000+0.j        , -0.63214782-0.50630509j,
        -0.11785218-0.2866272j , -0.11785218+0.2866272j ,
        -0.63214782+0.50630509j],
       [ 2.30000000+0.j        , -0.31180340-0.2590304j ,
        -0.08819660-0.13380304j, -0.08819660+0.13380304j,
        -0.31180340+0.2590304j ]])

In [72]:
a.sort()
print a

[[ 0.   0.   2.   2.   3. ]
 [ 3.   4.   4.   5.   6. ]
 [ 0.   0.   2.1  2.2  2.3]
 [ 0.   0.   2.4  2.5  2.6]
 [ 1.5  1.6  2.7  2.8  2.9]]


In [73]:
I = np.argsort(a[:,1])
b=a[I,:]
print b

[[ 0.   0.   2.   2.   3. ]
 [ 0.   0.   2.1  2.2  2.3]
 [ 0.   0.   2.4  2.5  2.6]
 [ 1.5  1.6  2.7  2.8  2.9]
 [ 3.   4.   4.   5.   6. ]]


In [74]:
np.linalg.lstsq(a,np.eye(5))

(array([[  3.00646474e-14,  -1.33333333e+00,   9.22222222e+01,
          -8.22222222e+01,   3.33333333e+00],
        [ -2.73543804e-14,   1.25000000e+00,  -8.58333333e+01,
           7.58333333e+01,  -2.50000000e+00],
        [  1.00000000e+00,   1.33048684e-14,  -7.66666667e+01,
           6.66666667e+01,  -4.09130717e-14],
        [ -2.00000000e+00,  -1.14491940e-14,   6.66666667e+01,
          -5.66666667e+01,   3.37841534e-14],
        [  1.00000000e+00,  -1.75780868e-15,   6.66666667e+00,
          -6.66666667e+00,   5.17356933e-15]]),
 array([], dtype=float64),
 5,
 array([  1.30774107e+01,   3.00208487e+00,   7.47592536e-01,
          2.64384156e-01,   4.63935270e-03]))

In [75]:
np.unique(a)

array([ 0. ,  1.5,  1.6,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,
        2.8,  2.9,  3. ,  4. ,  5. ,  6. ])

In [76]:
a.squeeze()

array([[ 0. ,  0. ,  2. ,  2. ,  3. ],
       [ 3. ,  4. ,  4. ,  5. ,  6. ],
       [ 0. ,  0. ,  2.1,  2.2,  2.3],
       [ 0. ,  0. ,  2.4,  2.5,  2.6],
       [ 1.5,  1.6,  2.7,  2.8,  2.9]])